
btnGuardar = document.getElementById('btnGuardar')
btnEditar = document.getElementById('btnEditar')
btnDelete = document.getElementById('btnDelete')
inventario = document.getElementById('inventario')
serie = document.getElementById('serie')
modelos = document.getElementById('modelos')
caracteristicas = document.getElementById('caracteristicas')
depto = document.getElementById('depto')
empresa = document.getElementById('empresa')
user = document.getElementById('user')
categoria = document.getElementById('categoria')
brand = document.getElementById('brand')
procesador = document.getElementById('procesador')
so = document.getElementById('so')
ram = document.getElementById('ram')
discoduro = document.getElementById('discoduro')
